server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;
    server_tokens off;

    location /api/ {
		proxy_pass ${API_URL};
	}

    # SPA routing
    location / {
        try_files $uri $uri/ /index.html;
    }
}